CREATE TABLE IF NOT EXISTS pessoas (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    eh_atendente BOOLEAN DEFAULT FALSE,
    eh_cliente BOOLEAN DEFAULT TRUE
);
